cars_club/cars/urls.py
from django.urls import path, re_path, register_converter
from . import views
from . import converters
from .views import CarsCategory, TagPostList

register_converter(converters.FourDigitYearConverter, "year4")

urlpatterns = [
    path('', views.CarsHome.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('addpage/', views.AddPage.as_view(), name='add_page'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.login, name='login'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    path('category/<slug:cat_slug>/', CarsCategory.as_view(), name='category'),
    path('tag/<slug:tag_slug>/', TagPostList.as_view(), name='tag'),
    path('edit/<slug:slug>/', views.UpdatePage.as_view(), name='edit_page'),
]

cars_club/cars_club/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from cars.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls')),
    path('users/', include('users.urls', namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Электромобили"

cars_club/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetDoneView, PasswordResetView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'),
    path('password-reset/', PasswordResetView.as_view(template_name="users/password_reset_form.html", email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")), name='password_reset'),
]
app_name = "users"

cars_club/templates/base.html
{% load static %}
{% load carstag %}
<!DOCTYPE html>
<html>
<head>
    <title>{{title}}</title>
    <link type="text/css" href="{% static 'cars/css/styles.css' %}" rel="stylesheet"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="{% static 'cars/images/main.ico' %}" type="image/x-icon"/>
    <meta name="viewport" content="width=device-width, initial-scale=0, user-scalable=no, width=950px">
</head>
<body>

<header>
    {% block mainmenu %}
    <a class="logo" href="{% url 'home' %}"><img src="{% static 'cars/images/logo.png' %}"></a>

    <ul class="main-menu">
        {% for m in mainmenu %}
        <li><a href="{% url m.url_name %}">{{m.title}}</a></li>
        {% endfor %}
    </ul>

    <div>
        {% if user.is_authenticated %}
        <a class="app-link" href="{% url 'users:profile' %}">{{user.username}}</a> | <a class="app-link" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
        <a class="app-link" href="{% url 'users:login' %}">Войти</a> | <a class="app-link" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </div>
    {% endblock mainmenu %}
</header>

<main>
    <div class="sidebar">
        <ul class="categories-list">
            {% if cat_selected == 0 %}
            <li class="selected">
                <img src="{% static 'cars/images/cars.png' %}">
                <span>Все категории</span>
            </li>
            {% else %}
            <li>
                <a href="{% url 'home' %}">
                    <img src="{% static 'cars/images/cars.png' %}">
                    <span>Все категории</span>
                </a>
            </li>
            {% endif %}

            {% show_categories cat_selected %}
        </ul>

        <div class="line"></div>

        {% show_all_tags %}

        <div class="line"></div>

        <div class="share">
            <p>Наш канал</p>
            <a class="share-yt" href="https://www.youtube.com" target="_blank" rel="nofollow">
                <img src="{% static 'cars/images/yt-logo.png' %}">
            </a>
        </div>
    </div>
    <div class="content-wrapper">

        <div class="content">
            {% block breadcrumbs %}
            {% endblock %}

            <div class="content-text">
                {% block content %}
                {% endblock %}
            </div>

            {% block navigation %}
            {% endblock %}
        </div>

        <footer>
            <p>&copy; 2024 Electrocar</p>
        </footer>
    </div>

</main>

</body>
</html>